spring.application.name=ragib-url-shortener

## App Config
app.base-url=http://localhost:8080
app.default-expiry-in-days=30
app.validate-original-url=true
app.page-size=10

## Disable Docker
spring.docker.compose.enabled=false

## Local H2 Database
# Stored on disk so local users and links survive application restarts.
spring.datasource.url=jdbc:h2:file:./data/url-shortener
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

## Disable Flyway
spring.flyway.enabled=false
